steps:
  - name: gcr.io/cloud-builders/yarn
    id: install
    entrypoint: "bash"
    args:
      - -ceux
      - |
        yarn install

  - name: gcr.io/cloud-builders/yarn
    id: build
    entrypoint: "bash"
    args:
      - -ceux
      - |
        export REACT_APP_AUTH0_DOMAIN="$_REACT_APP_AUTH0_DOMAIN"
        export REACT_APP_AUTH0_CLIENT_ID="$_REACT_APP_AUTH0_CLIENT_ID"
        export REACT_APP_AUTH0_AUDIENCE="$_REACT_APP_AUTH0_AUDIENCE"
        export REACT_APP_AUTH0_REDIRECT_URI="$_REACT_APP_AUTH0_REDIRECT_URI"
        yarn build

  - name: gcr.io/cloud-builders/gsutil
    id: deploy
    entrypoint: "bash"
    args:
      - -ceux
      - |
        gsutil cp -r build/* gs://$_WEBAPP_BUCKET_NAME
        gsutil cp build/* gs://$_WEBAPP_BUCKET_NAME
        gsutil cp  build/index.html gs://$_WEBAPP_BUCKET_NAME/index.html
        gsutil iam ch allUsers:objectViewer gs://$_WEBAPP_BUCKET_NAME
        gsutil web set -m index.html -e index.html gs://$_WEBAPP_BUCKET_NAME
logsBucket: $_LOGS_BUCKET_NAME
options:
  logging: GCS_ONLY
