steps:
  - name: gcr.io/cloud-builders/yarn
    id: install
    entrypoint: "bash"
    args:
      - -ceux
      - |
        yarn install

  - name: gcr.io/cloud-builders/yarn
    id: build
    entrypoint: "bash"
    args:
      - -ceux
      - |
        yarn build

  - name: gcr.io/cloud-builders/gsutil
    id: deploy
    entrypoint: "bash"
    args:
      - -ceux
      - |
        gsutil cp build/ gs://$$_WEBAPP_BUCKET_NAME
        gsutil iam ch allUsers:objectViewer gs://$$_WEBAPP_BUCKET_NAME
        gsutil web set -m index.html -e 404.html gs://$$_WEBAPP_BUCKET_NAME
