steps:
  - name: gcr.io/cloud-builders/yarn
    id: install-test-build
    entrypoint: "bash"
    args:
      - -ceux
      - |
        yarn install
        yarn test

        export REACT_APP_AUTH0_DOMAIN="$_REACT_APP_AUTH0_DOMAIN"
        export REACT_APP_AUTH0_CLIENT_ID="$_REACT_APP_AUTH0_CLIENT_ID"
        export REACT_APP_AUTH0_AUDIENCE="$_REACT_APP_AUTH0_AUDIENCE"
        export REACT_APP_AUTH0_REDIRECT_URI="$_REACT_APP_AUTH0_REDIRECT_URI"
        yarn build

  - name: us-central1-docker.pkg.dev/predyktv2/expert-dollup-common/firebase-deploy:latest
    args:
      - -ceux
      - |
        cp build /opt/firebase/build
        cd /opt/firebase
        firebase deploy --only hosting --project predyktv2

logsBucket: $_LOGS_BUCKET_NAME
options:
  logging: GCS_ONLY
